//
//  TestCard.m
//  dal-plugin
//
//  Created by John Boiles  on 5/8/20.
//

#import "TestCard.h"

#import <AppKit/AppKit.h>
#import "Defines.generated.h"

// This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
// http://www.paintcodeapp.com

void DrawTestCardWithFrame(CGContextRef context, NSRect frame)
{
    if (context == NULL) {
        context = NSGraphicsContext.currentContext.CGContext;
    }

    [NSGraphicsContext saveGraphicsState];

    //// Color Declarations
    NSColor* _0078d7 = [NSColor colorWithRed: 0 green: 0.471 blue: 0.843 alpha: 1];

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(0, 0, frame.size.width, frame.size.height)];
    [_0078d7 setFill];
    [rectanglePath fill];

    [NSGraphicsContext restoreGraphicsState];
}


NSImage *ImageOfTestCardWithSize(NSSize imageSize)
{
    return [NSImage imageWithSize: imageSize flipped: YES drawingHandler: ^(__unused NSRect dstRect)
    {
        DrawTestCardWithFrame(nil, NSMakeRect(0, 0, imageSize.width, imageSize.height));
        return YES;
    }];
}
